import diningOutCard_01 from '../../assets/diningoutCard/diningOut_01.webp';
import diningOutCard_02 from '../../assets/diningoutCard/diningOut_02.webp';
import diningOutCard_03 from '../../assets/diningoutCard/diningOut_03.webp';
import diningOutCard_04 from '../../assets/diningoutCard/diningOut_04.webp';
import diningOutCard_05 from '../../assets/diningoutCard/diningOut_05.webp';
import diningOutCard_06 from '../../assets/diningoutCard/diningOut_06.webp';
import diningOutCard_07 from '../../assets/diningoutCard/diningOut_07.webp';
import diningOutCard_08 from '../../assets/diningoutCard/diningOut_08.webp';
import diningOutCard_09 from '../../assets/diningoutCard/diningOut_09.webp';
import diningOutCard_10 from '../../assets/diningoutCard/diningOut_10.webp';
import diningOutCard_11 from '../../assets/diningoutCard/diningOut_11.webp';
import diningOutCard_12 from '../../assets/diningoutCard/diningOut_12.webp';

export const diningOutCardData = [
    {
        id: 1,
        restaurant_name: "Malad Social",
        restaurant_tag: "North Indian, Chinese",
        restaurant_address:"Inorbit Mall, Malad West, Mumbai",
        rating: 3.9,
        distance: 1.2,
        distance_unit:"km",
        price_for_two: 1500,
        openingTime: 11,
        coverPhoto:diningOutCard_01,
    },
    {
        id: 2,
        restaurant_name: "The Maverick Lounge",
        restaurant_tag: "Chinese, Italian, Continental",
        restaurant_address:"Malad West, Mumbai",
        rating: 3.9,
        distance: 118,
        distance_unit:"m",
        price_for_two: 1500,
        openingTime: 10,
        coverPhoto:diningOutCard_02,
    },
    {
        id: 3,
        restaurant_name: "Samvene - The Bagel Cafe",
        restaurant_tag: "Cafe, Salad, Continental",
        restaurant_address:"Malad West, Mumbai",
        rating: 4.3,
        distance: 1.4,
        distance_unit:"km",
        price_for_two: 900,
        openingTime: 0,
        coverPhoto:diningOutCard_03,
    },
    {
        id: 4,
        restaurant_name: "Conch Restaurants",
        restaurant_tag: "North Indian, Malwani",
        restaurant_address:"Malad West, Mumbai",
        rating: 3.9,
        distance: 1.1,
        distance_unit:"km",
        price_for_two: 1600,
        openingTime: 11,
        coverPhoto:diningOutCard_04,
    },
    {
        id: 5,
        restaurant_name: "Mam's By Banjara Dhaba",
        restaurant_tag: "Fast Food, Chinese, Mughlai",
        restaurant_address:"Malad West, Mumbai",
        rating: 3.4,
        distance: 1.3,
        distance_unit:"km",
        price_for_two: 700,
        openingTime: 11,
        coverPhoto:diningOutCard_05,
    },
    {
        id: 6,
        restaurant_name: "1441 Pizzeria",
        restaurant_tag: "Pizza, Italian, Pasta",
        restaurant_address:"Malad West, Mumbai",
        rating: 4.5,
        distance: 604,
        distance_unit:"m",
        price_for_two: 700,
        openingTime: 11,
        coverPhoto:diningOutCard_06,
    },
    {
        id: 7,
        restaurant_name: "Mini Punjab",
        restaurant_tag: "North Indian, Chinese",
        restaurant_address:"Malad West, Mumbai",
        rating: 3.6,
        distance: 1.1,
        distance_unit:"km",
        price_for_two: 1000,
        openingTime: 11,
        coverPhoto:diningOutCard_07,
    },
    {
        id: 8,
        restaurant_name: "Juliette Ristorante & Bar",
        restaurant_tag: "European, Italian, Dessert",
        restaurant_address:"Andheri Lokhandwala, Andheri West, Mumbai",
        rating: 3.8,
        distance: 4.7,
        distance_unit:"km",
        price_for_two: 1500,
        openingTime: 11,
        coverPhoto:diningOutCard_08,
    },
    {
        id: 9,
        restaurant_name: "Billy's Burgers",
        restaurant_tag: "Burger, Fast Food, Sandwich",
        restaurant_address:"Malad West, Mumbai",
        rating: 3.9,
        distance: 514,
        distance_unit:"m",
        price_for_two: 400,
        openingTime: 10,
        coverPhoto:diningOutCard_09,
    },
    {
        id: 10,
        restaurant_name: "The Joy Pizzateria",
        restaurant_tag: "Pizza, Fast Food",
        restaurant_address:"Malad West, Mumbai",
        rating: 4.3,
        distance: 478,
        distance_unit:"m",
        price_for_two: 400,
        openingTime: 11,
        coverPhoto:diningOutCard_10,
    },
    {
        id: 11,
        restaurant_name: "Cremure",
        restaurant_tag: "Bakery, Desserts, Fast Food",
        restaurant_address:"Malad West, Mumbai",
        rating: 3.8,
        distance: 238,
        distance_unit:"m",
        price_for_two: 500,
        openingTime: 10,
        coverPhoto:diningOutCard_11,
    },
    {
        id: 12,
        restaurant_name: "Shree Ramanjaneya Authentic",
        restaurant_tag: "Chinese, South Indian, Fast Food",
        restaurant_address:"Malad West, Mumbai",
        rating: 3.9,
        distance: 1.3,
        distance_unit:"km",
        price_for_two: 600,
        openingTime: 0,
        coverPhoto:diningOutCard_12,
    },
]
